//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Books = new HashSet<Book>();
        }
    
        public System.Guid id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<Book> Books { get; set; }
    }
}
